"use strict";
var __cov_2pSyHpJVP2ZGKbZO$iQ4Ow = (Function('return this'))();
if (!__cov_2pSyHpJVP2ZGKbZO$iQ4Ow.__coverage__) { __cov_2pSyHpJVP2ZGKbZO$iQ4Ow.__coverage__ = {}; }
__cov_2pSyHpJVP2ZGKbZO$iQ4Ow = __cov_2pSyHpJVP2ZGKbZO$iQ4Ow.__coverage__;
if (!(__cov_2pSyHpJVP2ZGKbZO$iQ4Ow['C:\\Users\\david\\Documents\\GitHub\\meta-confirm\\test\\mockedTestsWithErrors.js'])) {
   __cov_2pSyHpJVP2ZGKbZO$iQ4Ow['C:\\Users\\david\\Documents\\GitHub\\meta-confirm\\test\\mockedTestsWithErrors.js'] = {"path":"C:\\Users\\david\\Documents\\GitHub\\meta-confirm\\test\\mockedTestsWithErrors.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":0,"16":0,"17":0,"18":0,"19":0,"20":0},"b":{},"f":{"1":0,"2":0,"3":0,"4":0,"5":0},"fnMap":{"1":{"name":"(anonymous_1)","line":9,"loc":{"start":{"line":9,"column":72},"end":{"line":9,"column":84}}},"2":{"name":"(anonymous_2)","line":12,"loc":{"start":{"line":12,"column":15},"end":{"line":12,"column":31}}},"3":{"name":"(anonymous_3)","line":19,"loc":{"start":{"line":19,"column":14},"end":{"line":19,"column":30}}},"4":{"name":"(anonymous_4)","line":31,"loc":{"start":{"line":31,"column":54},"end":{"line":31,"column":70}}},"5":{"name":"(anonymous_5)","line":32,"loc":{"start":{"line":32,"column":74},"end":{"line":32,"column":97}}}},"statementMap":{"1":{"start":{"line":4,"column":0},"end":{"line":4,"column":48}},"2":{"start":{"line":5,"column":0},"end":{"line":5,"column":36}},"3":{"start":{"line":6,"column":0},"end":{"line":6,"column":33}},"4":{"start":{"line":7,"column":0},"end":{"line":7,"column":29}},"5":{"start":{"line":9,"column":0},"end":{"line":43,"column":3}},"6":{"start":{"line":12,"column":4},"end":{"line":17,"column":7}},"7":{"start":{"line":13,"column":8},"end":{"line":15,"column":61}},"8":{"start":{"line":16,"column":8},"end":{"line":16,"column":15}},"9":{"start":{"line":19,"column":4},"end":{"line":22,"column":7}},"10":{"start":{"line":20,"column":8},"end":{"line":20,"column":30}},"11":{"start":{"line":21,"column":8},"end":{"line":21,"column":15}},"12":{"start":{"line":25,"column":4},"end":{"line":25,"column":38}},"13":{"start":{"line":26,"column":4},"end":{"line":26,"column":28}},"14":{"start":{"line":27,"column":4},"end":{"line":27,"column":34}},"15":{"start":{"line":28,"column":4},"end":{"line":28,"column":129}},"16":{"start":{"line":31,"column":4},"end":{"line":40,"column":7}},"17":{"start":{"line":32,"column":8},"end":{"line":39,"column":10}},"18":{"start":{"line":35,"column":20},"end":{"line":35,"column":61}},"19":{"start":{"line":36,"column":20},"end":{"line":36,"column":48}},"20":{"start":{"line":37,"column":20},"end":{"line":37,"column":27}}},"branchMap":{}};
}
__cov_2pSyHpJVP2ZGKbZO$iQ4Ow = __cov_2pSyHpJVP2ZGKbZO$iQ4Ow['C:\\Users\\david\\Documents\\GitHub\\meta-confirm\\test\\mockedTestsWithErrors.js'];
__cov_2pSyHpJVP2ZGKbZO$iQ4Ow.s['1']++;var metaconfirm=require('../../meta-confirm');__cov_2pSyHpJVP2ZGKbZO$iQ4Ow.s['2']++;var expect=require('chai').expect;__cov_2pSyHpJVP2ZGKbZO$iQ4Ow.s['3']++;var request=require('request');__cov_2pSyHpJVP2ZGKbZO$iQ4Ow.s['4']++;var sinon=require('sinon');__cov_2pSyHpJVP2ZGKbZO$iQ4Ow.s['5']++;describe('Mocked Requests to check validation logic with Error on Get',function(){__cov_2pSyHpJVP2ZGKbZO$iQ4Ow.f['1']++;__cov_2pSyHpJVP2ZGKbZO$iQ4Ow.s['6']++;beforeEach(function(done){__cov_2pSyHpJVP2ZGKbZO$iQ4Ow.f['2']++;__cov_2pSyHpJVP2ZGKbZO$iQ4Ow.s['7']++;sinon.stub(request,'get').yields(new Error('test Error'),null,null);__cov_2pSyHpJVP2ZGKbZO$iQ4Ow.s['8']++;done();});__cov_2pSyHpJVP2ZGKbZO$iQ4Ow.s['9']++;afterEach(function(done){__cov_2pSyHpJVP2ZGKbZO$iQ4Ow.f['3']++;__cov_2pSyHpJVP2ZGKbZO$iQ4Ow.s['10']++;request.get.restore();__cov_2pSyHpJVP2ZGKbZO$iQ4Ow.s['11']++;done();});__cov_2pSyHpJVP2ZGKbZO$iQ4Ow.s['12']++;var url='http://www.caspar.com';__cov_2pSyHpJVP2ZGKbZO$iQ4Ow.s['13']++;var searchType='name';__cov_2pSyHpJVP2ZGKbZO$iQ4Ow.s['14']++;var searchTag='description';__cov_2pSyHpJVP2ZGKbZO$iQ4Ow.s['15']++;var content='Caspar Computer Services Inc.  Providing Innovative Solutions since 1984. Passionate about Agile Development';__cov_2pSyHpJVP2ZGKbZO$iQ4Ow.s['16']++;it('will not find the data if it does not exist',function(done){__cov_2pSyHpJVP2ZGKbZO$iQ4Ow.f['4']++;__cov_2pSyHpJVP2ZGKbZO$iQ4Ow.s['17']++;metaconfirm.FindInPage(url,searchType,searchTag+'X',content,function(err,result){__cov_2pSyHpJVP2ZGKbZO$iQ4Ow.f['5']++;__cov_2pSyHpJVP2ZGKbZO$iQ4Ow.s['18']++;expect(err.message).equals('test Error');__cov_2pSyHpJVP2ZGKbZO$iQ4Ow.s['19']++;expect(result).equals(null);__cov_2pSyHpJVP2ZGKbZO$iQ4Ow.s['20']++;done();});});});
