language: node_js

node_js:
  - "6.9.1"
  - "6.16.0"
  - "7.2.1"
  - "7.10.1"
  - "8.15.0"
  - "9.11.2"
  - "10.14.1"
  - "10.15.0"
  - "11.7.0"

before_install:
  - npm install jshint@latest

install:
  - npm ci

branches:
  only:
  - master

notifications:
  email:
    - david.sabine@live.com
